name: video_creator
version: 0.0.1
author: James Hurford <terrasea@gmail.com>
description: A polymer element to create a simple video from a series of images
dependencies:
  bwu_datagrid: any
  polymer: any
dev_dependencies:
  browser: any
  scheduled_test: any
transformers:
- polymer:
    entry_points:
      - example/index.html
      - test/index.html